### ISSUE TITLE
Arabic Videos Error

### ISSUE THREAD

**Issue by Trsj2019** [emadmahdi/KODI#13]
I have been using arabic videos program on Amazon TV firestick Kodi 17.6 krypton for long time and was working very good then suddenly a week ago it start to give error message attached is a photo for the error everytime I try to open kol el arab folder or Akwam folder to watch any movie or series I tried to uninstall and install again but no success I managed to view the kodi error log file and attached a screen shot too please try to fix ASAP or tell me what to do - I am living in Cairo Egypt and using this at my home.
Awaiting ur reply.
![20190527_023529](https://user-images.githubusercontent.com/51059359/58389517-83852180-802b-11e9-974b-9657bc474335.jpg)
![15589188299208557669688598552677](https://user-images.githubusercontent.com/51059359/58389568-da8af680-802b-11e9-88a6-140c398eaaf7.jpg)

**Comment by emadmahdi** [comment]
الخطأ الذي ارسلته لي يقول ان كودي غير قادر على التواصل المشفر مع موقع كل العرب وهذا قد يكون بسبب الموقع او بسبب جهازك او بسبب الانترنيت عندك او بسبب الانترنيت عندهم ... المعلومات غير كافية لتحديد المشكلة والاحتمالات كثيرة ولكن

 اولا اريد ان تجرب هذا الرابط 
https://vod.alarab.com/ramadan2019/مصرية
من المتصفح الموجود على نفس جهازك ال
Amazon TV firestick 
وتخبرني اذا كان الموقع الاصلي يعمل او لا

وثانيا اريد منك ان تقوم بتحديث برنامجي الى الاصدار الاخير ثم ترسل لي سجل الاخطاء انا اضفت هذه الوظيفة الى 
  برنامجي في بداية قائمة البرنامج

 ثالثا اريد منك ان تقوم بفحص الاتصال المشفر من برنامجي في نهاية قائمة البرنامج وتخبرني النتيجة

**Comment by Trsj2019** [comment]
The link u ask me to try is not working and gives error 520

**Comment by Trsj2019** [comment]
![15589847966867173435728452987500](https://user-images.githubusercontent.com/51059359/58436354-38b7e800-80c5-11e9-911c-a8a0d8eb332f.jpg)

**Comment by Trsj2019** [comment]
![15589849568462292871291130728342](https://user-images.githubusercontent.com/51059359/58436426-95b39e00-80c5-11e9-8f9a-bf77e99517da.jpg)

**Comment by Trsj2019** [comment]
![15589850460988878662062276913180](https://user-images.githubusercontent.com/51059359/58436468-cabff080-80c5-11e9-95fa-740421bfc064.jpg)

**Comment by emadmahdi** [comment]
Error 520 is essentially when something unexpected happens or when the origin server incorrectly interprets or does not tolerate a request due to a protocol violation or an empty response

هذا الخطأ معناه ان المشكلة من الموقع الاصلي ... عادة تكون هذه المشكلة مؤقته ... اما بسبب الاستخدام الكثير للموقع من العالم كله في وقت الذروة او ممكن بسبب ان السيرفر او الموقع بطيء في اوقات معينة او ممكن بسبب ان الموقع يتم تحديثه او تغير اشياء معينة فيه او ممكن بسبب منع الموقع من العمل في بعض الدول او بعض المناطق او غيرها من الاسباب الكثيرة الخارجة عن السيطرة

اسف المشكلة من الموقع الاصلي ... انا لا يوجد شيء استطيع عمله ... جرب استخدام مواقع اخرى في برنامجي

اذا كنت ما تزال تعتقد ان المشكلة من برنامجي فاذن ابعث لي سجل الاخطاء وذلك باستخدام برنامجي الاختيار رقم واحد في القائمة الرئيسية

**Comment by emadmahdi** [comment]
لكي تتأكد ان المشكلة ليست من جهازك ال
Amazon TV firestick
 حاول ان تدخل الى نفس رابط موقع كل العرب الذي ارسلته لك سابقا ولكن من جهاز ثاني في نفس بيتك فاذا دخل فهذا معناه ان جهازك الامازون فيه برنامج او مشكلة تمنع الجهاز من الوصول الى موقع كل العرب بصورة صحيحة واذا لم يدخل فاذن المشكلة هي من الانترنيت ومن خارج بيتك

**Comment by Trsj2019** [comment]
بالفعل انا جربت اكتر من جهاز عندى فى القاهرة و جميعهم بيظهروا نفس الخطاء و جربت جهاز اخر عند ابنتى فى لندن و كان شغال بس عمل نفس الاشكال عندها من اسبوع فمن الواضح انها مشكلة فى الانترنت سيرفيس فى بعض الدول لانه ساعات يشتغل و ساعات يظهر الخطاء ده عامة انا هتابع تانى وابلغ حضرتك
