### ISSUE TITLE
help with kodi

### ISSUE THREAD

**Issue by Alifoua** [emadmahdi/KODI#63]
Salam I have some problem with kodi set up see attached 
![screenshot016](https://user-images.githubusercontent.com/73899072/98008249-3db9b480-1dec-11eb-88b7-a1062d9302d4.png)
it looks font problem

**Comment by emadmahdi** [comment]
I just saw you message now ... I am sorry ... I don't know what kind of problem you are talking about ... the photo does not show anything ... If you need to have clean install of my addon and skins ... download kodiemad app from this url

http://tiny.cc/kodiemad

**Comment by Alifoua** [comment]
Salam .. I am 75year old !!!!!!!!!!!!! so i have a problem with kodi i need
to adjust font to fit the pix on the monitor

**Comment by emadmahdi** [comment]
i assume that you do understand arabic because my program is all in arabic ... that is why i reply to you in arabic

وعليكم السلام ورحمة الله
اهلا وسهلا بك

انت تحتاج الى جلد كودي تكون الكتابة فيه كبيرة ... انا عندي جلد قمت بتكبيره لكي يناسب الموبايل ولا اظن انك سوف تجد جلد 
 ثاني فيه كتابة اكبر من هذا الجلد ... وانا متأكد انك سوف تستفيد منه ... حمل ملف التطبيق من هذا الموقع ... التطبيق هو عبارة عن كودي ومدمج معه الجلد ومخزن عماد واعدادات كودي

http://tiny.cc/kodiemad

قبل ان تقوم بالتثبيت عليك ان تمسح كودي القديم واذا لم تكن تريد المسح فاذن انت تحتاج الى ان تغير اعدادات كودي بنفسك وايضا تقوم بتثبيت الجلد بنفسك

انا اعتذر مرة اخرى لاني لم انتبه الى رسالتك في وقت مبكر

**Comment by emadmahdi** [comment]
جلد كودي الذي اتكلم عنه اسمه
metropolisEMAD

وانا شخصيا استخدمه عندي على التلفزيون

**Comment by Alifoua** [comment]
Salam so happy that you have done your addon thanks my problem started two
years ago and they are as follow
1. when i applied kodi 17.6 I had sound put no picture so reset player to
videos / software and it works thanks God.
2. but when I update to 18 and to 18.9  I get sound no picture and reset of
videos dose not fix the problem Hum!!!!!!!!!!!!
3.if you have notice from the attach pic last pix of every word see time do
you know of any fix
I am residence in UK since 1970 if you need help here I will try to do as I
am disable and my pc is my gate newspaper books and TV thanks for your help
God bless

**Comment by emadmahdi** [comment]
Your problem most likely is a "graphic card driver" ... it is a small piece of software that connect hardware with software ... in your case it control the communication between your windows operating system and your lcd/led screen.

You can find more details in these pages ... other people also reported having the same problem and it was fixed by downgrading windows 10:

https://forum.kodi.tv/showthread.php?tid=332826
https://forum.kodi.tv/showthread.php?tid=335005
https://www.google.com/search?q=kodi+last+letter

**Comment by emadmahdi** [comment]
in general ... i do not advise downgrading windows ... but i advice updating windows and/or updating graphics card driver.

**Comment by emadmahdi** [comment]
if this problem is only when using kodi then go to kodi "settings" then to "player" settings and/or "system" settings and try to play with the settings.

**Comment by Alifoua** [comment]
Salam..many thanks for your kind advise.. it seem that I will have to live
with this problem  the rest of my life so it will be kodi and my disability
please make sure that your addon is compatible  with kodi 17.6 God bless

**Comment by emadmahdi** [comment]
wa alekum alsalam ... if you do not have access to windows update ... then you can download the driver of your "graphics card" and install it ... you just need to identify the model of your card and then download its driver from the internet.
